spring:
  application:
    name: namustutam-backend

  datasource:
    # Read from Render environment variables
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/namustute_db_pos}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

    # url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d88p9cek1jcs73fpc33g-a.oregon-postgres.render.com:5432/namustutam_db?sslmode=require}
    # username: ${SPRING_DATASOURCE_USERNAME:namustutam_db_user}
    # password: ${SPRING_DATASOURCE_PASSWORD:V1EyJzIg7Ca4vzf2X12tc8Oszb1eifxR}
    # driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:namustutam@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:OTPAPPAPI}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
            scope: email, profile

          facebook:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_ID:YOUR_FACEBOOK_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_SECRET:YOUR_FACEBOOK_CLIENT_SECRET}
            scope: email, public_profile

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 3000

app:
  base-url: ${APP_BASE_URL:http://localhost:3000}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  cors-extra-origins: ${CORS_EXTRA_ORIGINS:}


# app:
#   base-url: ${APP_BASE_URL:https://springboot-app-pb1v.onrender.com}
#   frontend-url: ${FRONTEND_URL:https://saa-s-namustutam.vercel.app}
#   cors-extra-origins: ${CORS_EXTRA_ORIGINS:}


jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

ai:
  encryption-secret: ${AI_ENCRYPTION_SECRET:6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b}
